/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyManejoArchivos;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author josej
 */
public class Pantalla extends javax.swing.JFrame {
    String ruta;
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos pdf", "pdf");
    Buscar buscar = new Buscar();
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel1.setVisible(false);
        Buscar.setVisible(false);
        lista.setVisible(false);
        jTextArea1.setVisible(false);
        txtMostrarDatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        version = new javax.swing.JTextField();
        pag = new javax.swing.JTextField();
        tam = new javax.swing.JTextField();
        fuente = new javax.swing.JTextField();
        bytes = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        lista = new javax.swing.JTextField();
        txtMostrarDatos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCargar = new javax.swing.JButton();
        btnElegir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lector PDF");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setText("Buscar archivo");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        Salida.setText("Salir");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField2.setText("Título:");

        jTextField4.setText("Tamaño: ");

        pag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagActionPerformed(evt);
            }
        });

        jTextField1.setText("Version PDF");

        jTextField5.setText("Numero de paginas ");

        jTextField6.setText("Tamaño de pagina");

        jTextField7.setText("Fuentes en PDF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tam, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fuente)
                        .addComponent(bytes, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(version, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(pag, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bytes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 350, 10));

        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        getContentPane().add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 250, -1));

        txtMostrarDatos.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtMostrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setText("Lector PDF");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 190, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 10, 10));

        btnCargar.setText("Seleccionar PDF");
        btnCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarMouseClicked(evt);
            }
        });
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 60));

        btnElegir.setText("Elegir Carpeta");
        btnElegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElegirMouseClicked(evt);
            }
        });
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalidaActionPerformed
private void carpeta(File archivo)
    {
       // jList1 = new javax.swing.JList<>();
        String temp = "";
        for (final File fileEntry : archivo.listFiles()) 
            {
             if (fileEntry.isDirectory()) {
      
            carpeta(fileEntry);
              } else {
                if (fileEntry.isFile()) {
                temp = fileEntry.getName();
                 if ((temp.substring(temp.lastIndexOf('.') + 1, temp.length()).toLowerCase()).equals("pdf"))
                 {
       
                     txtNombre.setText(fileEntry.getName());
                     String aux = archivo.getAbsolutePath()+ "\\" + fileEntry.getName();
                     File archivopdf = new File(aux);
                    lectorArchivosPDF(archivopdf);
                 }
                }

                }
           }
    }
/**private void archivoPDF(File archivo)
    {
        PDF pdf = new PDF(archivo);
          int a = pdf.metaDatos().split("/").length;
          String[] partir = pdf.metaDatos().split("/");
          System.out.println(pdf.metaDatos());
          System.out.println(pdf.paginas());
          version.setText(pdf.version());
          pag.setText(pdf.paginas());
          tam.setText(pdf.tamP());
          fuente.setText(pdf.fuentes() );
          bytes.setText(pdf.bytes());
      
    }

  **/

private void lectorArchivosPDF(File archivo)
    {
          String nombre = "";
          String autor = "";
          String creador = ""; 
          String fechaCreacion = ""; // 23
          String fechaModificacion = ""; // 23
          String productor="";
          String version=""; // 8
        int tamanio=0;
        int paginas=0;
        float tamaniox=0;
        float tamanioy=0;
        int imagenes=0;
        String fuentes=""; 
    
          PDF lector = new PDF(archivo);
          int a = lector.MetaDatos().split("/").length;
          String[] partir = lector.MetaDatos().split("/");
          //System.out.println("Los metadatos son:");
          //this.nombreArchivo.setText(archivo.getName());
          nombre=archivo.getName();
          String b = "";
          String c = "";
          boolean parentesis = false;
           for(int j=1; j<a; j++)
          {
           b = "";
           c = "";
           parentesis = false;
           //System.out.println(partir[j]);
             for(int i=1; i<partir[j].length(); i++)
             {
                 if(partir[j].charAt(i-1) ==  '(')
                 {
                     parentesis = true;
                 }
                  if(parentesis)   
                  {
                     if(partir[j].charAt(i) !=  ')')
                     {
                         b+=partir[j].charAt(i);
                     }
                     else{
                         parentesis = false;
                         break;
                     }
                  }
                  else{
                      c+=partir[j].charAt(i-1);
                  }
             }
             //System.out.println(c);
             if("Author".equals(c) || "Author ".equals(c))
             {
                 //System.out.println("Autor: " + b);
                 //this.autor.setText(b);
                 autor = b;
             }
             else if("Creator".equals(c) || "Creator ".equals(c))
             {
                 //System.out.println("Creador: " + b);
                 //this.Creador.setText(b);
                 creador = b;
             }
             else if("CreationDate".equals(c) || "CreationDate ".equals(c))
             {
                 //System.out.println("Fecha Creacion: " + b);
                 //this.FechaCreacion.setText(b);
                 fechaCreacion = b;
             }
             else if("ModDate".equals(c) || "ModDate ".equals(c))
             {
                 //System.out.println("Fecha Modificacion: " + b);
                 //this.FechaModificacion.setText(b);
                 fechaModificacion = b;
             }
             else if("Producer".equals(c) || "Producer ".equals(c))
             {
                 //System.out.println("Productor: " + b);
              //   this.Productor.setText(b);
                 productor =b;
             }
             else if("Title".equals(c) || "Title ".equals(c))
             {
                 //System.out.println("Titulo: " + b);
                 //this.autor.setText(b);                 
             }
             System.out.println(b);
          }
           
          System.out.println("La version del PDF es: " + lector.VersionPDF());
          System.out.println("Tamaño del archivo: " + lector.TamanioPDF() + " Bytes");
          System.out.println("Número de Páginas: "+lector.Paginas());
          lector.TamPag();
          System.out.println("Tamaño de Página: "+ lector.TamX() + " X " + lector.TamY() + " mm");
          System.out.println("Listado de Imágenes: "+ lector.LectorImagenes());
          System.out.println("Listado de Fuentes: " + lector.Fuentes());
          /*
          this.version.setText(lector.LecturaVersion());
          this.tamanio.setText(String.valueOf(lector.Tamanio()));
          this.numeroPaginas.setText(String.valueOf(lector.Numpaginas()));
          this.tamanioPaginasX.setText(String.valueOf(lector.getTamanioX()));    
          this.tamanioPaginasY.setText(String.valueOf(lector.getTamanioY())); 
          this.imagenes.setText(String.valueOf(lector.LectorImagenes()));
          this.fuentes.setText(lector.LectordeFuentes());*/
          
            //version.setText(lector.VersionPDF());
          //pag.setText(lector.Paginas());
          //tam.setText(lector.TamPag());
          fuente.setText(lector.Fuentes() );
          bytes.setText(lector.bytes());
          txtMostrarDatos.setText(fuentes);
          
          version = lector.VersionPDF();
          tamanio = lector.TamanioPDF();
         System.out.println(); paginas = lector.Paginas();
          tamaniox = lector.TamX();
          tamanioy = lector.TamY();
          imagenes = lector.LectorImagenes();
          fuentes = lector.Fuentes();
         // lista.InsertarM(nombre,autor,creador,fechaCreacion,fechaModificacion,productor,version,tamanio,paginas,tamaniox,tamanioy,imagenes,fuentes);                
          //aux = lista.getFrente();
          System.out.println();
          
    }

    
    public void buscar1(String dir){
      
             
                File carpeta = new File(dir);
                File[] archivos = carpeta.listFiles();
                String[] listado = carpeta.list(); 
                 
                      lista.setText("LISTADO CON OBJETOS File" );
                  if (archivos == null || archivos.length == 0) {
                 lista.setText("No hay elementos dentro de la carpeta actual");
                  return;
                }  
                
                else {
                  SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
  
                  for (int i=0; i< archivos.length; i++) {
                       if (listado[i].endsWith(".pdf") || listado[i].endsWith(".PDF")){ /// verifica si es pdf o no
                    File archivo = archivos[i];
                    lista.setText(String.format("%s (%s) - %d - %s", 
                                                      archivo.getName(), 
                                                      
                                                      archivo.isDirectory() ? "Carpeta" : "Archivo",
                                                      
                                                      archivo.length(),
                                                      
                                                      sdf.format(archivo.lastModified())
                            
                                                      ));
                  }
                }
                }
       
}
    
    
    
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElegirActionPerformed

    private void btnCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMouseClicked

        // TODO add your handling code here:
         FrmArchivoDatos f2=new FrmArchivoDatos();
        f2.setVisible(true);
    }//GEN-LAST:event_btnCargarMouseClicked

    private void btnElegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElegirMouseClicked

        // TODO add your handling code here:
        FormAbrirArchivo f1=new FormAbrirArchivo();
        f1.setVisible(true);
    }//GEN-LAST:event_btnElegirMouseClicked

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
        // String lista = buscar.buscar(ruta);
        ///para mostrar lo que muestra la clase buscar.buscar

        //String texto =  buscar.buscar(ruta);
        //lista.add(buscar.buscar(ruta));

        // lista.setText(texto);

        //buscar.buscar(ruta);

    }//GEN-LAST:event_listaActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:

        // buscar.sCarpAct= selectorArchivo;
        // selectorArchivo.setFileFilter(filtro);
        // int resultado = selectorArchivo.showOpenDialog(this);

        ///colocamos ruta

        JFileChooser selectorArchivo = new JFileChooser();
        selectorArchivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int opcion = selectorArchivo.showOpenDialog(this);
        if ( opcion == JFileChooser.APPROVE_OPTION ){
            File dir = selectorArchivo.getSelectedFile();
            ruta =dir.getAbsolutePath();
            if ( dir.isDirectory())
            {
                carpeta(dir);

                //PDF pdf = new PDF(dir);
                //  System.out.println("paginas" +  pdf.Numpaginas());
            }
            else if(dir.isFile())
            {
                lectorArchivosPDF(dir);
                //  buscar1(ruta);
            }
            //  buscar.buscar1(ruta);
            //  buscar1(ruta);
            // buscar.LecturaVersion(dir);
            //nomas pa probar si envia la ruta
            //  buscar.buscar1(ruta);
            //

            // }
        //BUSCAR 1 EN BUSCAR

        //  lista.setText(buscar.buscar(ruta));
        // String texto =  buscar.buscar(ruta);

        // String nombre = selectorArchivo.getSelectedFile().getName();

        //String ruta = selectorArchivo.getSelectedFile().getPath();

        //long tamano = selectorArchivo.getSelectedFile().getTotalSpace();

        //Asignacion de datos
        /// txtNombre.setText(nombre);
        // txtRuta.setText(ruta);
        // txtTamano.setText(Long.toString(tamano));
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void pagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Salida;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnElegir;
    private javax.swing.JTextField bytes;
    private javax.swing.JTextField fuente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lista;
    private javax.swing.JTextField pag;
    private javax.swing.JTextField tam;
    private javax.swing.JLabel txtMostrarDatos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField version;
    // End of variables declaration//GEN-END:variables
}
